### ISSUE TITLE
Failed to import profile: Line is too long

### ISSUE THREAD

**Issue by cemdorst** [paulmarsicloud/terraform-aws-openvpn-ephemeral#16]
Everything went fine on the Terraform side:
```
module.openvpn-ephemeral.null_resource.obtain_ovpn_file (local-exec): fatal error: An error occurred (404) when calling the HeadObject operation: Key "openvpn.ovpn" does not exist
module.openvpn-ephemeral.null_resource.obtain_ovpn_file (local-exec): ls: openvpn.ovpn: No such file or directory
module.openvpn-ephemeral.null_resource.obtain_ovpn_file: Still creating... [1m0s elapsed]
module.openvpn-ephemeral.null_resource.obtain_ovpn_file (local-exec): Completed 6.9 KiB/6.9 KiB (9.7 KiB/s) with 1 file(s) remaining
module.openvpn-ephemeral.null_resource.obtain_ovpn_file (local-exec): download: s3://terraform-20230801220018334600000001/openvpn.ovpn to ./openvpn.ovpn
module.openvpn-ephemeral.null_resource.obtain_ovpn_file (local-exec): openvpn.ovpn
module.openvpn-ephemeral.null_resource.obtain_ovpn_file: Creation complete after 1m7s [id=2983115070959307466]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 9 added, 0 changed, 0 destroyed.
```

The final step of importing the openvpn.ovpn profile crashes with the following message: "Failed to import profile: Line is too long"

<img width="394" alt="Captura de Tela 2023-08-01 às 19 08 28" src="https://github.com/paulmarsicloud/terraform-aws-openvpn-ephemeral/assets/1277578/1669d80e-c31b-4195-bf00-6f4e9226a7b1">

I am using OpenVPN Connect 3.4.2 (4547)

I also tried to use tunnelblick 4.0.0. Similar error message:
```
     
          1690928399.626361 b000 Options error: In /Library/Application Support/Tunnelblick/Users/dorst/openvpn.tblk/Contents/Resources/config.ovpn:4: Maximum option line length (256) exceeded, line starts with remote <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name=
          1690928399.626584 1040 Use --help for more information.
          
     More details may be in the Console Log's "All Messages"
```

**Comment by paulmarsicloud** [comment]
Hi @cemdorst

First off - my sincerest apologies for the delay in this reply!! I have had some crazy life changes as of recent and my beloved  terraform-aws-openvpn-ephemeral project has not been on the high list of priorities at this time!

Can you please confirm you are using the latest tag [v1.1.0](https://github.com/paulmarsicloud/terraform-aws-openvpn-ephemeral/releases/tag/v1.1.0) on your side?

Thanks!

Paul

**Comment by cemdorst** [comment]
Hi Paul, no problem! I hope that the life changes came in at a good time!

So, about your lovely module, yes, I am using 1.1.0. Looking at it, I would say it is something with the [openvpn-install](https://github.com/angristan/openvpn-install)  script. It is generating the `remote` config line with a lot of unnecessary stuff, exceeding the length limit. If I just replace all the line by `remote <my ec2 public IP>` everything works.
